function [] = parforsave(save_fname,tau_collect,pGeo_collect,z_collect,...
                         corr_mat_collect,joint_loglik_collect,rho_record_collect,...
                         time_taken,M,N,n_quadrature_points,constrain_rho,...
                         params)
%PARFORSAVE saves results of simulation in parfor 



save(save_fname,'tau_collect','pGeo_collect','z_collect',...
                'corr_mat_collect','joint_loglik_collect','rho_record_collect',...
                'time_taken','M','N','n_quadrature_points','constrain_rho',...
                'params');


end

